connectedapp/urls.py
from django.urls import path, include
from . import views

app_name = 'connectedapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile_change/', views.profile_change, name='profile_change'),
    path('accounts/register/', views.register, name='register'),

    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/create/', views.UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),

    path('edupdates/', views.StatusListView.as_view(), name='status_list'),
    path('edupdates/create/', views.StatusCreateView.as_view(), name='status_create'),
    path('edupdates/<int:pk>/edit/', views.StatusUpdateView.as_view(), name='status_update'),
    path('edupdates/<int:pk>/delete/', views.StatusDeleteView.as_view(), name='status_delete'),

    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('courses/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('courses/<int:pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('courses/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),

    path('courses/<int:pk>/feedbacks/create/', views.FeedbackCreateView.as_view(), name='feedback_create'),
    path('feedbacks/<int:pk>/edit/', views.FeedbackUpdateView.as_view(), name='feedback_update'),
    path('feedbacks/<int:pk>/delete/', views.FeedbackDeleteView.as_view(), name='feedback_delete'),

    path('courses/<int:course_id>/enroll/', views.CourseEnrollView.as_view(), name='course_enroll'),
    path('courses/<int:course_id>/unenroll/<int:student_id>/', views.CourseUnenrollView.as_view(), name='course_unenroll'),

    path('notifications/<int:notification_id>/read/', views.notification_mark_as_read, name='notification_mark_as_read'),

    path('chat/<str:room_name>/', views.chat, name='chat'),
    path('chat/<str:room_name>/post_message/', views.chat_post_message, name='chat_post_message'),
    path('chat/<str:room_name>/get_messages/', views.chat_get_messages, name='chat_get_messages'),
    path('chat/<str:room_name>/clear/', views.chat_clear_room, name='chat_clear_room'),

]

connectedproject/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from connectedapp.views import CustomUserViewSet, CourseViewSet, FeedbackViewSet, NotificationViewSet, RoleViewSet, StatusViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'users', CustomUserViewSet)
router.register(r'courses', CourseViewSet)
router.register(r'feedbacks', FeedbackViewSet)
router.register(r'notifications', NotificationViewSet)
router.register(r'roles', RoleViewSet)
router.register(r'statuses', StatusViewSet)

urlpatterns = [
    path('', include('connectedapp.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

connectedapp/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from .models import CustomUser, Status, Course, Feedback

class CustomUserChangeForm(UserChangeForm):
    password = None  # Exclude the password field from the form
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'bio', 'location', 'birth_date')
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 4}),
            'birth_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'bio', 'location', 'birth_date',)
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 4}),
            'birth_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
        }


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'description', 'teacher', 'students', 'files']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'students': forms.SelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.fields['teacher'].queryset = CustomUser.objects.filter(roles__name='Teacher')
        self.fields['students'].queryset = CustomUser.objects.filter(roles__name='Student')


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }

connectedapp/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, RedirectView, View
from .models import CustomUser, Role, Status, Course, Feedback, Notification, Message
from .forms import CustomUserChangeForm, CustomUserCreationForm, StatusForm, CourseForm, FeedbackForm
from rest_framework import viewsets, permissions
from .serializers import RoleSerializer, CustomUserSerializer, StatusSerializer, CourseSerializer, FeedbackSerializer, NotificationSerializer
import json

class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    permission_classes = [permissions.IsAuthenticated]

class RoleViewSet(viewsets.ModelViewSet):
    queryset = Role.objects.all()
    serializer_class = RoleSerializer
    permission_classes = [permissions.IsAuthenticated]

class StatusViewSet(viewsets.ModelViewSet):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer
    permission_classes = [permissions.IsAuthenticated]

class CourseViewSet(viewsets.ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = [permissions.IsAuthenticated]

class FeedbackViewSet(viewsets.ModelViewSet):
    queryset = Feedback.objects.all()
    serializer_class = FeedbackSerializer
    permission_classes = [permissions.IsAuthenticated]

class NotificationViewSet(viewsets.ModelViewSet):
    queryset = Notification.objects.all()
    serializer_class = NotificationSerializer
    permission_classes = [permissions.IsAuthenticated]


def index(request):
    notifications = Notification.objects.filter(user=request.user, is_read=False) if request.user.is_authenticated else None
    return render(request, 'index.html', {'notifications': notifications})


@login_required
def profile(request):
    return render(request, 'registration/profile.html', {'user': request.user})


@login_required
def profile_change(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('connectedapp:profile')
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'registration/profile_change_form.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Assign the "Student" role to the user
            student_role = Role.objects.get(name='Student')
            user.roles.add(student_role)
            user.save()

            login(request, user)
            return redirect('connectedapp:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


class TeacherRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_teacher()


class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    context_object_name = 'users'
    template_name = 'user_list.html'


class UserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    context_object_name = 'user_detail'
    template_name = 'user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status_form'] = StatusForm()
        context['statuses'] = self.object.statuses.all()
        return context


class UserCreateView(LoginRequiredMixin, TeacherRequiredMixin, CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'user_form.html'
    success_url = reverse_lazy('connectedapp:user_list')


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'user_form.html'

    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    def get_success_url(self):
        return reverse_lazy('connectedapp:user_detail', kwargs={'pk': self.object.pk})


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CustomUser
    template_name = 'user_confirm_delete.html'
    success_url = reverse_lazy('connectedapp:user_list')

    def test_func(self):
        user = self.get_object()
        return self.request.user == user


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    context_object_name = 'statuses'
    template_name = 'status_list.html'

    def get_queryset(self):
        return Status.objects.all().order_by('-created_at')

class StatusCreateView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'status_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user  # Automatically set the user to the current user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('connectedapp:user_detail', kwargs={'pk': self.object.user.pk})


class StatusUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'status_form.html'

    def test_func(self):
        status = self.get_object()
        return self.request.user == status.user  # Only allow the user who created the status to edit it

    def get_success_url(self):
        return reverse_lazy('connectedapp:user_detail', kwargs={'pk': self.object.user.pk})


class StatusDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Status
    template_name = 'status_confirm_delete.html'

    def test_func(self):
        status = self.get_object()
        return self.request.user == status.user  # Only allow the user who created the status to delete it

    def get_success_url(self):
        return reverse_lazy('connectedapp:user_detail', kwargs={'pk': self.object.user.pk})


class CourseListView(ListView):
    model = Course
    context_object_name = 'courses'
    template_name = 'course_list.html'


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'course_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feedback_form'] = FeedbackForm()
        context['feedbacks'] = self.object.feedbacks.all()
        return context


class CourseCreateView(LoginRequiredMixin, TeacherRequiredMixin, CreateView):
    model = Course
    form_class = CourseForm
    template_name = 'course_form.html'
    success_url = reverse_lazy('connectedapp:course_list')


class CourseUpdateView(LoginRequiredMixin, TeacherRequiredMixin, UpdateView):
    model = Course
    form_class = CourseForm
    template_name = 'course_form.html'
    success_url = reverse_lazy('connectedapp:course_list')


class CourseDeleteView(LoginRequiredMixin, TeacherRequiredMixin, DeleteView):
    model = Course
    context_object_name = 'course'
    template_name = 'course_confirm_delete.html'
    success_url = reverse_lazy('connectedapp:course_list')


class FeedbackCreateView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    template_name = 'feedback_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = get_object_or_404(Course, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.course = Course.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('connectedapp:course_detail', kwargs={'pk': self.object.course.pk})


class FeedbackUpdateView(UpdateView):
    model = Feedback
    form_class = FeedbackForm
    template_name = 'feedback_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = self.object.course
        return context

    def get_queryset(self):
        return Feedback.objects.all().order_by('-created_at')

    def get_success_url(self):
        return reverse_lazy('connectedapp:course_detail', kwargs={'pk': self.object.course.pk})


class FeedbackDeleteView(DeleteView):
    model = Feedback
    template_name = 'feedback_confirm_delete.html'
    success_url = reverse_lazy('connectedapp:feedback_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = self.object.course
        return context

    def get_success_url(self):
        return reverse_lazy('connectedapp:course_detail', kwargs={'pk': self.object.course.pk})


class CourseEnrollView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('connectedapp:course_detail', kwargs={'pk': self.kwargs.get('course_id')})

    def post(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs.get('course_id'))
        course.students.add(request.user)
        Notification.objects.create(
            user=course.teacher,
            text=f"{request.user.get_full_name()} has enrolled in your course '{course.name}'."
        )
        messages.success(request, "You've successfully enrolled in the course.")
        return super().post(request, *args, **kwargs)

connectedapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}ConnectEd{% endblock title %}</title>

  <!-- Load Bootstrap 5 CSS -->
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'connectedapp:index' %}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="20px" height="20px" class="mb-1"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M96 0C43 0 0 43 0 96V416c0 53 43 96 96 96H384h32c17.7 0 32-14.3 32-32s-14.3-32-32-32V384c17.7 0 32-14.3 32-32V32c0-17.7-14.3-32-32-32H384 96zm0 384H352v64H96c-17.7 0-32-14.3-32-32s14.3-32 32-32zm32-240c0-8.8 7.2-16 16-16H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H144c-8.8 0-16-7.2-16-16zm16 48H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H144c-8.8 0-16-7.2-16-16s7.2-16 16-16z"/></svg></i> ConnectEd</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'connectedapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:status_list' %}">EdUpdates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:user_list' %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:course_list' %}">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:chat' 'ConnectEd' %}">Chat</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link me-3">Hello, {{ user.username }}!</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" onclick="logout();">Logout</a>
            <script>
              function logout() {
                var form = document.createElement('form');
                form.method = 'POST';
                form.action = '{% url "connectedapp:logout" %}';  <!-- Ensure this URL is correctly configured -->

                // CSRF token
                var csrfInput = document.createElement('input');
                csrfInput.type = 'hidden';
                csrfInput.name = 'csrfmiddlewaretoken';
                csrfInput.value = '{{ csrf_token }}';
                form.appendChild(csrfInput);

                document.body.appendChild(form);
                form.submit();
              }
            </script>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'connectedapp:register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    {% if messages %}
      <div class="container mt-3">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    {% block content %}{% endblock %}
  </div>

  <!-- Load Bootstrap 5 and dependencies -->
  {% bootstrap_javascript %}

  <!-- Your custom scripts here -->

</body>
</html>

connectedapp/templates/course_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <h2>Course Details</h2>
  <div class="card mt-3">
    <div class="card-header">
      {{ course.name }}
    </div>
    <div class="card-body">
      <h5 class="card-title">Course Details</h5>
      <p class="card-text"><strong>Description:</strong> {{ course.description }}</p>
      <p class="card-text"><strong>Teacher:</strong> {{ course.teacher.get_full_name }}</p>

      <h5 class="mt-4">Enrolled Students</h5>
      {% if course.students.all %}
        <ul class="list-group list-group-flush">
          {% for student in course.students.all %}
          <a href="{% url 'connectedapp:user_detail' student.pk %}" class="list-group-item list-group-item-action">
            {{ student.get_full_name }}
            {% if request.user == course.teacher %}
              <form action="{% url 'connectedapp:course_unenroll' course.pk student.pk %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm float-end">Unenroll</button>
              </form>
            {% endif %}
          </a>
          {% endfor %}
        </ul>
      {% else %}
        <p class="text-muted">No students are currently enrolled in this course.</p>
      {% endif %}

      <h5 class="mt-4">Course Files</h5>
      {% if course.files %}
        <a href="{{ course.files.url }}" class="btn btn-primary mt-3" download>Download Course Materials</a>
      {% else %}
        <p class="text-muted">No files available for this course.</p>
      {% endif %}

      <h5 class="mt-4">Course Feedback</h5>
      {% for feedback in feedbacks %}
        <p class="card-text">{{ feedback.text }}</p>
        <footer class="blockquote-footer">{{ feedback.user.get_full_name }} on <cite title="Source Title">{{ feedback.created_at|date:"Y-m-d" }}</cite></footer>
        {% if user.is_authenticated and feedback.user == request.user %}
          <div class="mb-3">
            <a href="{% url 'connectedapp:feedback_update' feedback.pk %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'connectedapp:feedback_delete' feedback.pk %}" class="btn btn-danger">Delete</a>
          </div>
        {% endif %}
      {% empty %}
        <p class="text-muted">No feedback available for this course.</p>
      {% endfor %}

      {% if request.user.is_authenticated and request.user.is_student %}
        <h5 class="mt-4">Leave Feedback</h5>
          <form method="post" action="{% url 'connectedapp:feedback_create' course.pk %}">
            {% csrf_token %}
            {% bootstrap_form feedback_form %}
            <button type="submit" class="btn btn-primary">Submit Feedback</button>
          </form>
      {% endif %}
    </div>
  </div>
  {% if request.user.is_authenticated and request.user.is_student and request.user not in course.students.all %}
    <form action="{% url 'connectedapp:course_enroll' course.id %}" method="post" class="mt-3">
      {% csrf_token %}
       <button type="submit" class="btn btn-primary">Enroll</button>
       <a href="{% url 'connectedapp:course_list' %}" class="btn btn-secondary">Back to Courses</a>
    </form>
  {% endif %}
</div>
{% endblock %}

connectedapp/templates/course_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <h2>Courses</h2>
  {% if user.is_authenticated and user.is_teacher %}
    <a href="{% url 'connectedapp:course_create' %}" class="btn btn-primary mb-3 mt-3">Add New Course</a>
  {% endif %}
  <div class="row">
    {% for course in courses %}
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">{{ course.name }}</h5>
          <p class="card-text">{{ course.description|truncatechars:150 }}</p>
          {% if user.is_authenticated %}
            <a href="{% url 'connectedapp:course_detail' course.pk %}" class="btn btn-outline-primary">View</a>
          {% endif %}
          {% if user.is_authenticated and user.is_teacher %}
            <a href="{% url 'connectedapp:course_update' course.pk %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'connectedapp:course_delete' course.pk %}" class="btn btn-danger">Delete</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

connectedapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="notifications">
      {% for notification in notifications %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          {{ notification.text }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" onclick="location.href='{% url 'connectedapp:notification_mark_as_read' notification.id %}'"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <!-- Hero section -->
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Welcome to ConnectEd!</h1>
      <p class="col-md-8 fs-4">ConnectEd offers a premier platform for universities to present their courses, facilitating collaboration and knowledge sharing. We empower universities, students, and educators in the pursuit of excellence in education.</p>
      <button class="btn btn-primary btn-lg" type="button">Learn more</button>
    </div>
  </div>

  <!-- Additional content -->
  <div class="row align-items-md-stretch">
    <div class="col-md-6">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2>Courses</h2>
        <p>See the list of available courses and enroll in the ones that interest you.</p>
        <a href="{% url 'connectedapp:course_list' %}" class="btn btn-outline-light" type="button">View Courses</a>
      </div>
    </div>
    <div class="col-md-6">
      <div class="h-100 p-5 bg-light border rounded-3">
        <h2>Testimonials</h2>
        <p>See what our students and educators have to say about ConnectEd.</p>
        <a href="#" class="btn btn-outline-secondary" type="button">View Testimonials</a>
      </div>
    </div>
  </div>
{% endblock %}

connectedapp/templates/status_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <h2>EdUpdates</h2>
  <a href="{% url 'connectedapp:status_create' %}" class="btn btn-primary mb-3 mt-3">Submit EdUpdate</a>
  {% for status in statuses %}
  <div class="card mb-3">
    <div class="card-body">
      <p class="card-text">{{ status.text }}</p>
      <footer class="blockquote-footer">
        Posted by {{ status.user.get_full_name }} on <cite title="Source Title">{{ status.created_at|date:"Y-m-d H:i" }}</cite>
      </footer>
      {% if user.is_authenticated and status.user == request.user %}
        <a href="{% url 'connectedapp:status_update' status.pk %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'connectedapp:status_delete' status.pk %}" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
  {% empty %}
  <p>No status updates available.</p>
  {% endfor %}
</div>
{% endblock %}

connectedapp/templates/user_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <h2>Student Details</h2>
  <div class="card mt-3">
    <div class="card-header">
      {{ user_detail.get_full_name }}
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Username:</strong> {{ user_detail.username }}</p>
      <p class="card-text"><strong>Email:</strong> {{ user_detail.email }}</p>
      {% if user.bio %}
        <p class="card-text"><strong>Bio:</strong> {{ user.bio }}</p>
      {% endif %}
      {% if user.location %}
        <p class="card-text"><strong>Location:</strong> {{ user.location }}</p>
      {% endif %}
      {% if user.birth_date %}
        <p class="card-text"><strong>Birth Date:</strong> {{ user.birth_date|date:"F d, Y" }}</p>
      {% endif %}
      <p class="card-text"><strong>Roles:</strong> {% for role in user_detail.roles.all %}{{ role.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
      <h5 class="mt-4">EdUpdates</h5>
      {% for status in statuses %}
      <p class="card-text">{{ status.text }}</p>
      <footer class="blockquote-footer">{{ status.created_at|date:"Y-m-d H:i" }}</footer>
      {% empty %}
          <p>No status EdUpdates to show.</p>
      {% endfor %}
      </div>
  </div>
  {% if user.is_authenticated and user_detail == request.user %}
    <a href="{% url 'connectedapp:user_update' user_detail.pk %}" class="btn btn-primary mt-3">Edit</a>
    <a href="{% url 'connectedapp:user_delete' user_detail.pk %}" class="btn btn-danger mt-3">Delete</a>
  {% endif %}
  <a href="{% url 'connectedapp:user_list' %}" class="btn btn-secondary mt-3">Back to Students</a>
</div>
{% endblock %}